// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBflj2NlfLvJGpZ_WMkBFRc5KgJxtOZho',
    appId: '1:292651812775:web:2a93c8575c5acbc564d882',
    messagingSenderId: '292651812775',
    projectId: 'chat-app2-216dd',
    authDomain: 'chat-app2-216dd.firebaseapp.com',
    storageBucket: 'chat-app2-216dd.firebasestorage.app',
    measurementId: 'G-J2RSEQ8MR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXSwfEoIKFtfQHAD5HswOiI2jMxjoUGw4',
    appId: '1:292651812775:android:e74dbd5a10cbf66264d882',
    messagingSenderId: '292651812775',
    projectId: 'chat-app2-216dd',
    storageBucket: 'chat-app2-216dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAdQC32CvzWUnOAlw99kF-SmsrPdPapI',
    appId: '1:292651812775:ios:20e23d0cac2a2b9464d882',
    messagingSenderId: '292651812775',
    projectId: 'chat-app2-216dd',
    storageBucket: 'chat-app2-216dd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBflj2NlfLvJGpZ_WMkBFRc5KgJxtOZho',
    appId: '1:292651812775:web:74824c6790494f8364d882',
    messagingSenderId: '292651812775',
    projectId: 'chat-app2-216dd',
    authDomain: 'chat-app2-216dd.firebaseapp.com',
    storageBucket: 'chat-app2-216dd.firebasestorage.app',
    measurementId: 'G-B6F9C305KR',
  );
}
